dist: xenial

language: node_js

node_js:
  - "8"

stages:
  - lint
  - deploy

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make && make docker/run target=lint
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-tardigrade-keystore
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-aws-tardigrade-keystore v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-tardigrade-keystore/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: XMgTBLh/i3lnzLSuHyWrlJfEQ+R4O5xARuWWTbVqIwjqVRrohhqrWGxKN8itlpxEuUQ2axzmTloArYq572SffxbJ1zG3zrTQqt3sjgwOEiOkgU0MjhThqIZJ0SwKwLVxL7Pfa0CTcmwgkVByI2lanbIdDXJTrQ+fxyrpOFwIWHR305W5eA2unNv7biymm8xO1/i4HUOnNShPrNZ69Y3RfmCqNAGJhtH96MazPjjgPIhOZVTXVJ9GSsg/48hcydayeowSS5A4vTQ/cHyvrXX9xlviAAorzLe45u7U5MvcwR6EvOqC+588MlmZtv4T8V7QUTnRUprWmm7CMW69deb9ZYe4uVDy57NILCL0xzxJts/wfP0/YFqKm/3sz5nU0ZEetu43zXL4qz3po1Ws5s+U7Md5cC6DfsdXTlWPrt7AxEnKQKc1IjvTJNwseeuVdzxcmB8T9madC1oQQw2CZbw7NpdjNpnzmWUCRVZ2rgxrJMWLQu+6phkKkLBkIuaekRTz9ZqBCOdwmo0v5NjVSPVyYvKxliAd2uXELc4FxbXUMNHh4UKM/GJeFnMhw46PSnfhQwz3K7Di7otNpOJZWH2Xxqer0/4u+nyrnSNLb8vTdvfyChVGPeqr02Hs/S/v+PkOPZRwn0Pp242oSiHgOolf7aR2vcLpyphnHBd9yOlaDfw=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-tardigrade-keystore
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
