version: 1

update_configs:

  - package_manager: "terraform"
    directory: "/"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/create_s3_keystore"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/create_ssm_keystore"
    update_schedule: "daily"

  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
